POST http://127.0.0.1:8000/api/v1/auth/registro
Accept: application/json
Content-Type: application/json

{
 "name": "admin",
 "email": "admin57@admin.com",
 "password": "admin54321"
}

###login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: : application/json
Content-Type: application/json

{
    "email" : "admin57@admin.com",
    "password" : "admin54321"
}

### Perfil user
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 19|laravel_sanctum_Ebj8B7m3iU6TergGjwjaOgPaAro2nlRid6LL1XVU77c3751f

### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 19|laravel_sanctum_Ebj8B7m3iU6TergGjwjaOgPaAro2nlRid6LL1XVU77c3751f

