POST http://127.0.0.1:8000/api/v1/auth/registro
Accept: application/json
Content-Type: application/json

{
 "name": "jizarra",
 "email": "jizarra69@hotmail.com",
 "password": "jib54321"
}

###login
POST http://127.0.0.1:8000/api/v1/auth/login
Accept: : application/json
Content-Type: application/json

{
    "email" : "jizarra69@hotmail.com",
    "password" : "jib54321"
}

### Perfil user
GET http://127.0.0.1:8000/api/v1/auth/perfil
Accept: application/json
Authorization: Bearer 23|laravel_sanctum_gDq2c90TnadUTRFcpNGEl38chJMsuNPMBxwceSVD002e5b73

### Salir
POST http://127.0.0.1:8000/api/v1/auth/logout
Accept: application/json
Authorization: Bearer 23|laravel_sanctum_gDq2c90TnadUTRFcpNGEl38chJMsuNPMBxwceSVD002e5b73
